"""empty message

Revision ID: 019da77ba02d
Revises: 4f2e19bc2a27
Create Date: 2020-07-09 04:07:23.926213

"""
from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision = '019da77ba02d'
down_revision = '4f2e19bc2a27'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('package_review', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=datetime.datetime.utcnow().isoformat()))
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column('package_review', 'created_at')
	# ### end Alembic commands ###
