"""empty message

Revision ID: 86512692b770
Revises: ba730ce1dc3e
Create Date: 2020-07-11 01:56:28.634661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86512692b770'
down_revision = 'ba730ce1dc3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log_entry', sa.Column('description', sa.Text, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log_entry', 'description')
    # ### end Alembic commands ###
