"""empty message

Revision ID: 886c92dc6eaa
Revises: 8d22def23c8b
Create Date: 2020-12-15 16:38:54.114559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '886c92dc6eaa'
down_revision = '8d22def23c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package_update_config',
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('last_commit', sa.String(length=41), nullable=True),
    sa.Column('trigger', sa.Enum('COMMIT', 'TAG', name='packageupdatetrigger'), nullable=False),
    sa.Column('make_release', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('package_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package_update_config')
    # ### end Alembic commands ###
