"""empty message

Revision ID: 8d22def23c8b
Revises: 42b14763c95e
Create Date: 2020-12-10 22:23:32.291613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d22def23c8b'
down_revision = 'a9c1c08bf956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('cover_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'package', 'package_screenshot', ['cover_image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'package', type_='foreignkey')
    op.drop_column('package', 'cover_image_id')
    # ### end Alembic commands ###
