"""empty message

Revision ID: a337bcc165c0
Revises: f565dde93553
Create Date: 2021-01-29 21:30:37.277197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a337bcc165c0'
down_revision = 'f565dde93553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_update_config', sa.Column('outdated_at', sa.DateTime(), nullable=True))
    op.add_column('package_update_config', sa.Column('last_tag', sa.String(length=41), nullable=True))
    op.drop_column('package_update_config', 'outdated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_update_config', sa.Column('outdated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('package_update_config', 'outdated_at')
    op.drop_column('package_update_config', 'last_tag')
    # ### end Alembic commands ###
