"""empty message

Revision ID: ea5a023711e0
Revises: fa12fadbdb40
Create Date: 2018-05-26 01:55:09.745881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5a023711e0'
down_revision = 'fa12fadbdb40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute("ALTER TYPE userrank ADD VALUE 'BANNED'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
