"""empty message

Revision ID: ead35f7d446c
Revises: 81e0eb07a3cd
Create Date: 2018-05-23 19:39:29.216273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead35f7d446c'
down_revision = '81e0eb07a3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('package', 'forums',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('package', 'forums',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
