"""empty message

Revision ID: f30031f0b928
Revises: 83622276d439
Create Date: 2018-05-23 18:19:07.428378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30031f0b928'
down_revision = '83622276d439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('package_release', 'task_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=37),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('package_release', 'task_id',
               existing_type=sa.String(length=37),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
