"""empty message

Revision ID: fa12fadbdb40
Revises: c4152f4240ed
Create Date: 2018-05-25 18:46:54.039870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa12fadbdb40'
down_revision = 'c4152f4240ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_screenshot', sa.Column('approved', sa.Boolean(), nullable=False, server_default="true"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('package_screenshot', 'approved')
    # ### end Alembic commands ###
